-- AlterTable
ALTER TABLE "ContentItem" ADD COLUMN "video1Url" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentItem" ADD COLUMN "video1Desc" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentItem" ADD COLUMN "video2Url" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentItem" ADD COLUMN "video2Desc" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentItem" ADD COLUMN "video3Url" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentItem" ADD COLUMN "video3Desc" TEXT NOT NULL DEFAULT '';
